//+build !sqlg

// Code generated by sqlg DO NOT EDIT

package oracle

import (
	"bytes"
	"context"
	"fmt"
	"github.com/clementauger/sqlg/example/first/model"
	sqlg "github.com/clementauger/sqlg/runtime"
	"github.com/clementauger/sqlg/tpl"
	"text/template"
)

var queryTemplates026b37 = map[string]*template.Template{
	"myDatastore__DeleteManyAuthors": template.Must(template.New("").Funcs(tpl.FuncMap()).Parse(
		`DELETE FROM authors WHERE id IN ( {{.ids | collect $.SQLGValues $.SQLGFlavor | placeholder $.SQLGValues $.SQLGFlavor}} )`,
	)),
}

var rawQueries026b37 = map[string]string{
	"myDatastore__DeleteAuthors": `DELETE FROM authors WHERE bio = ''`,
}

func (m *MyDatastore) CreateSomeValues(ctx context.Context, db sqlg.Execer, v model.SomeType) (id int64, err error) {
	err = fmt.Errorf("unsupported")
	return
}

func (m *MyDatastore) DeleteAuthors(ctx context.Context, db sqlg.Execer) (err error) {
	var sqlQuery026b37 string
	sqlQuery026b37 = rawQueries026b37["myDatastore__DeleteAuthors"]

	m.Logger.Log("github.com/clementauger/sqlg/example/first/myDatastore", "DeleteAuthors", sqlQuery026b37)
	m.Tracer.Begin("github.com/clementauger/sqlg/example/first/myDatastore", "DeleteAuthors", sqlQuery026b37)
	defer func() {
		m.Tracer.End("github.com/clementauger/sqlg/example/first/myDatastore", "DeleteAuthors", err)
	}()

	_, err = db.ExecContext(ctx, sqlQuery026b37)
	if err != nil {
		return
	}
	return
}

func (m *MyDatastore) DeleteManyAuthors(ctx context.Context, db sqlg.Execer, ids []int) (_ []model.Author, err error) {
	var sqlQuery026b37 string
	SQLGValues026b37 := &[]interface{}{}
	SQLGFlavor026b37 := "?"
	{
		var query026b37 bytes.Buffer
		templateInput026b37 := map[string]interface{}{
			"SQLGConverter": m.Converter,
			"SQLGValues":    SQLGValues026b37,
			"SQLGFlavor":    SQLGFlavor026b37,
			"ids":           ids,
			"err":           err,
		}
		err = queryTemplates026b37["myDatastore__DeleteManyAuthors"].Execute(&query026b37, templateInput026b37)
		if err != nil {
			return
		}
		sqlQuery026b37 = query026b37.String()

		m.Logger.Log("github.com/clementauger/sqlg/example/first/myDatastore", "DeleteManyAuthors", sqlQuery026b37, (*SQLGValues026b37)...)
		m.Tracer.Begin("github.com/clementauger/sqlg/example/first/myDatastore", "DeleteManyAuthors", sqlQuery026b37, (*SQLGValues026b37)...)
		defer func() {
			m.Tracer.End("github.com/clementauger/sqlg/example/first/myDatastore", "DeleteManyAuthors", err)
		}()
	}

	_, err = db.ExecContext(ctx, sqlQuery026b37, (*SQLGValues026b37)...)
	if err != nil {
		return
	}
	return
}
