//+build !sqlg

// Code generated by sqlg DO NOT EDIT

package mssql

import (
	"bytes"
	"context"
	"fmt"
	"github.com/clementauger/sqlg/example/first/model"
	sqlg "github.com/clementauger/sqlg/runtime"
	tpl "github.com/clementauger/sqlg/tpl/mssql"
	"text/template"
)

var queryTemplatese1ab94 = map[string]*template.Template{
	"myDatastore__DeleteManyAuthors": template.Must(template.New("").Funcs(tpl.FuncMap()).Parse(
		`DELETE FROM authors WHERE id IN ( {{.ids | collect $.SQLGValues $.SQLGFlavor | placeholder $.SQLGValues $.SQLGFlavor}} )`,
	)),
}

var rawQueriese1ab94 = map[string]string{
	"myDatastore__DeleteAuthors": `DELETE FROM authors WHERE bio = ''`,
}

func (m *MyDatastore) CreateSomeValues(ctx context.Context, db sqlg.Execer, v model.SomeType) (id int64, err error) {
	err = fmt.Errorf("unsupported")
	return
}

func (m *MyDatastore) DeleteAuthors(ctx context.Context, db sqlg.Execer) (err error) {
	var sqlQuerye1ab94 string
	sqlQuerye1ab94 = rawQueriese1ab94["myDatastore__DeleteAuthors"]

	m.Logger.Log("github.com/clementauger/sqlg/example/first/myDatastore", "DeleteAuthors", sqlQuerye1ab94)
	m.Tracer.Begin("github.com/clementauger/sqlg/example/first/myDatastore", "DeleteAuthors", sqlQuerye1ab94)
	defer func() {
		m.Tracer.End("github.com/clementauger/sqlg/example/first/myDatastore", "DeleteAuthors", err)
	}()

	_, err = db.ExecContext(ctx, sqlQuerye1ab94)
	if err != nil {
		return
	}
	return
}

func (m *MyDatastore) DeleteManyAuthors(ctx context.Context, db sqlg.Execer, ids []int) (_ []model.Author, err error) {
	var sqlQuerye1ab94 string
	SQLGValuese1ab94 := &[]interface{}{}
	SQLGFlavore1ab94 := "@n"
	{
		var querye1ab94 bytes.Buffer
		templateInpute1ab94 := map[string]interface{}{
			"SQLGConverter": m.Converter,
			"SQLGValues":    SQLGValuese1ab94,
			"SQLGFlavor":    SQLGFlavore1ab94,
			"ids":           ids,
			"err":           err,
		}
		err = queryTemplatese1ab94["myDatastore__DeleteManyAuthors"].Execute(&querye1ab94, templateInpute1ab94)
		if err != nil {
			return
		}
		sqlQuerye1ab94 = querye1ab94.String()

		m.Logger.Log("github.com/clementauger/sqlg/example/first/myDatastore", "DeleteManyAuthors", sqlQuerye1ab94, (*SQLGValuese1ab94)...)
		m.Tracer.Begin("github.com/clementauger/sqlg/example/first/myDatastore", "DeleteManyAuthors", sqlQuerye1ab94, (*SQLGValuese1ab94)...)
		defer func() {
			m.Tracer.End("github.com/clementauger/sqlg/example/first/myDatastore", "DeleteManyAuthors", err)
		}()
	}

	_, err = db.ExecContext(ctx, sqlQuerye1ab94, (*SQLGValuese1ab94)...)
	if err != nil {
		return
	}
	return
}
